### ISSUE TITLE
Adapter Crash

### ISSUE THREAD

**Issue by m4xcube** [PfisterDaniel/iobroker.apple-find-me#1]
Hi, ich probiere gerade das Adapter aus, da die anderen Find Me Adapter anscheinend nicht laufen.
Leider Crasht dieses, da es anscheinend eine ID nicht zuordnen kann.
Es gibt bei meinem Profil zwei iPhones mit dem Namen "Michael-iPhone" die nicht mehr in verwendung sind.

Anbei der Log aus IO-Broker:

`apple-find-me.0	2021-04-24 14:25:26.937	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:25:26.936	info	terminating
apple-find-me.0	2021-04-24 14:25:26.875	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:25:26.874	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:25:26.869	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:25:26.868	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:25:26.754	info	4 Devices found
apple-find-me.0	2021-04-24 14:25:25.640	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:25:25.639	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:25:25.556	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16
apple-find-me.0	2021-04-24 14:24:52.777	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:24:52.776	info	terminating
apple-find-me.0	2021-04-24 14:24:52.722	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:24:52.721	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:24:52.718	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:24:52.717	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:24:52.619	info	4 Devices found
apple-find-me.0	2021-04-24 14:24:51.563	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:24:51.562	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:24:51.493	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16
apple-find-me.0	2021-04-24 14:24:18.582	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:24:18.581	info	terminating
apple-find-me.0	2021-04-24 14:24:18.533	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:24:18.533	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:24:18.529	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:24:18.529	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:24:18.429	info	4 Devices found
apple-find-me.0	2021-04-24 14:24:17.536	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:24:17.534	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:24:17.470	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16
apple-find-me.0	2021-04-24 14:19:48.246	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:19:48.244	info	terminating
apple-find-me.0	2021-04-24 14:19:47.930	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:19:47.929	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:19:47.925	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:19:47.923	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:19:47.785	info	4 Devices found
apple-find-me.0	2021-04-24 14:19:46.708	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:19:46.707	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:19:46.628	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16
apple-find-me.0	2021-04-24 14:19:13.818	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.CurrentLocation" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.766	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.RefreshTimeStamp" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.765	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.TimeStamp" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.764	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.Accuracy" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.763	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.PositionType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.762	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.Altitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.762	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.Longitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.761	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.Location.Latitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.759	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.CurrentLocation" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.758	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.RefreshTimeStamp" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.757	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.TimeStamp" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.756	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.Accuracy" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.755	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.PositionType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.754	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.Altitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.753	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.Longitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.752	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.Location.Latitude" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:19:13.744	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:19:13.742	info	terminating
apple-find-me.0	2021-04-24 14:19:13.675	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:19:13.674	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:19:13.670	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:19:13.669	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:19:13.547	info	4 Devices found
apple-find-me.0	2021-04-24 14:19:12.490	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:19:12.489	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:19:12.425	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16
apple-find-me.0	2021-04-24 14:13:29.785	warn	Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
apple-find-me.0	2021-04-24 14:13:29.710	error	adapter disabled
apple-find-me.0	2021-04-24 14:12:57.415	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.415	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.415	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.414	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.413	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.413	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.407	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.406	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.404	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.DeviceID, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.403	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelImage, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.403	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.BatteryState, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.402	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.BatteryLevel, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.401	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelName, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.400	warn	redis get apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelType, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.399	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.399	warn	get state error: Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.390	warn	redis get apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.DeviceID, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.389	warn	redis get apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.ModelImage, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.388	warn	redis get apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.BatteryState, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.387	warn	redis get apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.BatteryLevel, error - Connection is closed.
apple-find-me.0	2021-04-24 14:12:57.288	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.DeviceID" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.287	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelImage" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.285	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.BatteryState" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.284	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.BatteryLevel" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.283	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelName" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.281	warn	State "apple-find-me.0.iPhone.98xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx21.ModelType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.260	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.DeviceID" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.232	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.ModelImage" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.231	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.BatteryState" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.230	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.BatteryLevel" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.229	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.ModelName" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.228	warn	State "apple-find-me.0.iPhone.FAxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9E.ModelType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.224	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.DeviceID" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.210	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.ModelImage" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.210	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.BatteryState" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.209	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.BatteryLevel" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.208	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.ModelName" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:57.207	warn	State "apple-find-me.0.iPad.29xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxBD.ModelType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.867	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
apple-find-me.0	2021-04-24 14:12:56.866	info	terminating
apple-find-me.0	2021-04-24 14:12:56.847	warn	State "apple-find-me.0.iPhone..DeviceID" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.846	warn	State "apple-find-me.0.iPhone..ModelImage" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.845	warn	State "apple-find-me.0.iPhone..BatteryState" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.844	warn	State "apple-find-me.0.iPhone..BatteryLevel" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.843	warn	State "apple-find-me.0.iPhone..ModelName" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.841	warn	State "apple-find-me.0.iPhone..ModelType" has no existing object, this might lead to an error in future versions
apple-find-me.0	2021-04-24 14:12:56.827	error	The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:12:56.827	error	Error: The id "iPhone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:25 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:621:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:915:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:703:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:880:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:924:7) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12)
apple-find-me.0	2021-04-24 14:12:56.823	error	unhandled promise rejection: The id "iPhone." is invalid. Ids are not allowed to end in "."
apple-find-me.0	2021-04-24 14:12:56.823	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
apple-find-me.0	2021-04-24 14:12:56.718	info	4 Devices found
apple-find-me.0	2021-04-24 14:12:55.598	info	Refresh every 5 minutes
apple-find-me.0	2021-04-24 14:12:55.597	info	Starting Adapter Apple-Find-Me
apple-find-me.0	2021-04-24 14:12:55.498	info	starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v12.22.1, js-controller: 3.2.16`

**Comment by PfisterDaniel** [comment]
Hallo Michael,
dafür hab ich aktuell keine schnelle Lösung. Aber evtl hilft es wenn du die nicht verwendeten Geräte in deinem Account entfernst. 
Dies kannst du schnell und einfach über die Icloud-Page machen.

Gruß Daniel

**Comment by m4xcube** [comment]
Hi Daniel, 
danke, hat funktioniert.

Gruß,
Michael
