### ISSUE TITLE
Mehrere Istanzen

### ISSUE THREAD

**Issue by vonCartman** [PfisterDaniel/ioBroker.apple-find-me#10]
Hi,
als erstes ich danke dir. Es funktioniert einwandfrei.
Allerdings mit einer Instanz.
Die zweite (Andere AppleID) ist zwar grün, aber es werden keine objekte dazu erstellt.

**Comment by AFPass** [comment]
Ich hab 3 Instanzen. Alles grün. Was steht im Log?

**Comment by vonCartman** [comment]
es gibt kein Eintrag für die zweite Instanz.

![image](https://user-images.githubusercontent.com/65015881/159564063-28054755-1615-4ab1-b3dd-82344703e5aa.png)
![image](https://user-images.githubusercontent.com/65015881/159564123-c49e340c-f935-4546-8fac-30e6b5d49e50.png)
![image](https://user-images.githubusercontent.com/65015881/159564162-ce7c9991-d4a6-46df-a42c-714e9171996f.png)

**Comment by PfisterDaniel** [comment]
Seltsam, ich nutze auch 2 Instanzen und beide funktionieren einwandfrei.
Wie AFPass schon schrieb, was steht den in den Logs?

**Comment by vonCartman** [comment]
@PfisterDaniel wo finde ich die logs?

Sind das nicht die Protokolle?

**Comment by Apollon77** [comment]
Im Admin oder einfach /opt/iobroker/log/...

**Comment by vonCartman** [comment]
@Apollon77 

in /opt/ habe ich kein iobroker ordner. Nur 'pigpio' und 'WidevineCdm'

**Comment by vonCartman** [comment]
@Apollon77: RasPi

aber ich habs gefunden

![image](https://user-images.githubusercontent.com/65015881/159674911-021f31c0-6c90-41dc-9f11-2fb8245e8f27.png)

**Comment by vonCartman** [comment]
habt ihr eine idee woran es liegen kann?

**Comment by PfisterDaniel** [comment]
Nicht direkt, lt. findet er keine Geräte auf dieser Instanz. Hast du es mal nur mit diesen Logindaten versucht? Also Quasi eine Instanz 0 mit den Logindaten von der jetzigen Instanz 1?

**Comment by vonCartman** [comment]
nach dem ich die AppleIDs getauscht habe funktioniert alles.
