### ISSUE TITLE
iPhone Ton abspielen

### ISSUE THREAD

**Issue by Trrw** [PfisterDaniel/ioBroker.apple-find-me#11]
Hallo und danke für diesen Adapter! 
Wäre es möglich die Wiedergabe von einem Ton zu implementieren?
In iCloud nennt sich die Funktion "Ton abspielen" um das Gerät zu finden.

Danke!

**Comment by PfisterDaniel** [comment]
Hallo,

Ja das ist möglich. Ich werde mir eine Lösung überlegen und es implementieren. 

Gruß Daniel

**Comment by PfisterDaniel** [comment]
Fixed with version 0.0.13
