### ISSUE TITLE
Adapter Anzeige in ioBroker

### ISSUE THREAD

**Issue by AFPass** [PfisterDaniel/ioBroker.apple-find-me#15]
Hallo,

der Adapter wir sowohl unter NPM als auch unter GitHub nicht richtig in ioBroker angezeigt:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/13101074/162210308-0fa7b577-0e9d-4d97-a2fc-9493be0c5c73.png">

**Comment by Apollon77** [comment]
Yes because it is not officially in the repository yet ... is fixed by merging https://github.com/ioBroker/ioBroker.repositories/pull/1725
