### ISSUE TITLE
Adapter wird nicht unter Instanzen angezeigt

### ISSUE THREAD

**Issue by Goeste** [PfisterDaniel/ioBroker.apple-find-me#16]
Hallo, ich habe den Adapter über die URL installiert, da lieft auch alles ohne Probleme durch. nun taucht der Adapter aber nicht unter den Instanzen auf...

ABER es wurden objekte angelegt, wenn auch nur das "admin" folder..

auch ein restart von ioBroker hat nicht geholfen... ist das normal?

LG, goeste

**Comment by Apollon77** [comment]
Bei einem GitHub Install muss die Instanz immer manuell angelegt werden. Das "+" drücken in der Zeile des Adapters

**Comment by Goeste** [comment]
Danke dafür!!!
