### ISSUE TITLE
Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes.

### ISSUE THREAD

**Issue by MarkSau** [PfisterDaniel/ioBroker.apple-find-me#17]
Hi.
erstmal danke, das du diesen Adapter gemacht hast. Nun wollte ich ihn mal testen, bekomme aber leider den Fehler

"<html>
<body>

Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes. (3/3)
--

</body>
</html>"

obwohl ich eigentlich alles richtig unter Credentials eingeben haben sollte.  Die 2FA ist bei mir allerdings aktiv, was ich eigentlich auch nicht änder möchte. Liegt es vielleicht daran?

**Comment by PfisterDaniel** [comment]
Hi,

also eigentlich liegt es nicht an der 2FA. Die ist auch bei mir aktiv. Bist du dir sicher das deine ICloud Zugangsdaten wirklich richtig sind?

**Comment by MarkSau** [comment]
Ja...ich habe gerade auch mal mein Passwort geändert.

**Comment by MarkSau** [comment]
Log:
<html>
<body>


apple-find-me.0 | 2022-04-26 12:42:31.563 | error | Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes. (2/3)
-- | -- | -- | --
apple-find-me.0 | 2022-04-26 12:42:30.287 | error | Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes. (1/3)
apple-find-me.0 | 2022-04-26 12:42:28.943 | info | Refresh every 5 minutes
apple-find-me.0 | 2022-04-26 12:42:28.942 | info | Starting Adapter Apple-Find-Me
apple-find-me.0 | 2022-04-26 12:42:28.872 | info | starting. Version 0.0.12 (non-npm: PfisterDaniel/ioBroker.apple-find-me#19a4f40c3a3309dc37bcc7d92858742b11fd93a3) in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v14.19.1, js-controller: 4.0.23


</body>
</html>

**Comment by PfisterDaniel** [comment]
kannst du mal einen ScreenShot deiner Adaptereinstellungen machen? Bitte Nutzernamen und ggf. API-Keys anonymisieren.

**Comment by MarkSau** [comment]
![image](https://user-images.githubusercontent.com/22911084/165284503-8b49e700-a2e4-4763-b30a-06699ad7db89.png)

**Comment by MarkSau** [comment]
Hi..schon eine Idee?

**Comment by PfisterDaniel** [comment]
Hallo,

nein leider bin ich gerade etwas ratlos.... Ich habe bei mir alles soweit mal getestet. Es funktioniert bei mir ohne Probleme...

**Comment by MarkSau** [comment]
Leider gibt der "Alles" Log auch nicht viel her... ein genaueren Debug gibt es nicht.

<html>
<body>


apple-find-me.0 | 2022-04-27 10:22:16.527 | error | Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes. (2/3)
-- | -- | -- | --
apple-find-me.0 | 2022-04-27 10:22:15.322 | error | Error on HTTP-Request. Please check your credentials. StatusCode: 500 Retry in 5 minutes. (1/3)
apple-find-me.0 | 2022-04-27 10:22:13.877 | info | Refresh every 5 minutes
apple-find-me.0 | 2022-04-27 10:22:13.877 | info | Starting Adapter Apple-Find-Me
apple-find-me.0 | 2022-04-27 10:22:13.805 | info | starting. Version 0.0.12 (non-npm: PfisterDaniel/ioBroker.apple-find-me#19a4f40c3a3309dc37bcc7d92858742b11fd93a3) in /opt/iobroker/node_modules/iobroker.apple-find-me, node: v14.19.1, js-controller: 4.0.23
apple-find-me.0 | 2022-04-27 10:22:13.286 | debug | States connected to redis: 127.0.0.1:9000
apple-find-me.0 | 2022-04-27 10:22:13.177 | debug | States create User PubSub Client
apple-find-me.0 | 2022-04-27 10:22:13.176 | debug | States create System PubSub Client
apple-find-me.0 | 2022-04-27 10:22:13.133 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
apple-find-me.0 | 2022-04-27 10:22:13.087 | debug | Objects connected to redis: 127.0.0.1:9001
apple-find-me.0 | 2022-04-27 10:22:13.080 | debug | Objects client initialize lua scripts
apple-find-me.0 | 2022-04-27 10:22:12.932 | debug | Objects create User PubSub Client
apple-find-me.0 | 2022-04-27 10:22:12.931 | debug | Objects create System PubSub Client
apple-find-me.0 | 2022-04-27 10:22:12.928 | debug | Objects client ready ... initialize now
apple-find-me.0 | 2022-04-27 10:22:12.857 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>

**Comment by MarkSau** [comment]
hi..es könnte an einem Fehler des Zertifikats liegen, das von apple kommt.
im Browser bekomme ich beim aufruf von https://fmipmobile.icloud.com/fmipservice/device/test@test.de/initClient

NET::ERR_CERT_AUTHORITY_INVALID

und wenn ich da gleiche im linux mit curl aufrufe:

```
root@MSNUC-IOB:~# curl https://fmipmobile.icloud.com/fmipservice/device/test@test.de/initClient
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

**Comment by PfisterDaniel** [comment]
Nein, da sollte kein Zeichen sein. Ich verstehe auch nicht warum er das bei deiner Instanz macht. Denn Adapter nutzen ja mehrerer Leute und der Fehler scheint noch nicht aufgetreten zu sein.

**Comment by MarkSau** [comment]
Habe ich auch schon gemacht..reboot auch..

**Comment by MarkSau** [comment]
Hi...es lag wohl an meiner Eingabe der Apple-ID. Mein Autofill im Browser hat da wohl einen Streich gespielt und dieses "Sonderzeichen" hinten an geschmuggelt. Nach manueller Eingabe hats geklappt.  Soll das Issue geschlossen oder gelöscht werden?

**Comment by PfisterDaniel** [comment]
Hi, sehr gut das es nun klappt. Ich werde das Issue hiermit schließen.

Danke für die Rückmeldung
