### ISSUE TITLE
Kürzeren Refresh Intervall 

### ISSUE THREAD

**Issue by MarkSau** [PfisterDaniel/ioBroker.apple-find-me#18]
Hallo,
ich möchte deinen Adapter für die Anwesenheitskontrolle nutzen. Der 5minütige Refresh ist zwar beim Verlassen der "Home Zone" nützlich und auch ok, aber bei der Wiederkehr eher hinderlich. Um die Anwesenheit schneller zu erkennen, wäre hier ein kürzerer Zeitraum notwendig.

**Comment by PfisterDaniel** [comment]
Hallo,

das kann man schon anpassen, doch kommt es hierbei vermehrt zu Timeout-Fehlern. Des weiteren erhöht es den Akku-Verbrauch wirklich enorm. Nach 5x Timeout deaktiviert sich der Adapter...

Aber du kannst es selbst einbauen, indem du [hier](https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/19a4f40c3a3309dc37bcc7d92858742b11fd93a3/admin/index_m.html#L859)
einfach eine neue Zeile bsp: ` <option value="2" class="translate">Every 2 minutes</option>` hinzufügst...

**Comment by Apollon77** [comment]
Ggf auch Rate Limiting von Apple Seite? Ich denke das das nicht so simpel ist

**Comment by PfisterDaniel** [comment]
> Ggf auch Rate Limiting von Apple Seite? Ich denke das das nicht so simpel ist

Ja ich gehe davon aus, eventuell erzeugt auch ein Limit die Timeout-Fehler. Ich habe damals zur Vorsicht das deaktivieren des Adapters eingebaut, nicht das hierdurch noch der Account gesperrt wird...

Nach dem es ja keine offizielle API darstellt wird man nichts dokumentiertes diesbezüglich finden.

**Comment by Stormbringer11** [comment]
@MarkSau Das Problem kannst einfach umschiffen mit dem YAHK Adapter. Erstelle einfach eine Automation am iPhone, wenn du zu Hause verlässt/eintriffst > entsprechenden Datenpunkt true/false setzen.
