### ISSUE TITLE
Adapter stürzt ab

### ISSUE THREAD

**Issue by fighterzg6** [PfisterDaniel/ioBroker.apple-find-me#2]
Hallo, die Datenbank des adapters stürzt ab! wegen einem Zeichen im Gerätenamen.

apple-find-me.0 | 2022-02-02 07:29:16.889 | error | The id "iPad." is invalid. Ids are not allowed to end in "."
-- | -- | -- | --
apple-find-me.0 | 2022-02-02 07:29:16.888 | error | Error: The id "iPad." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3387:17) at /opt/iobroker/node_modules/iobroker.apple-find-me/main.js:147:29 at done (/opt/iobroker/node_modules/urllib/lib/urllib.js:589:5) at /opt/iobroker/node_modules/urllib/lib/urllib.js:948:9 at decodeContent (/opt/iobroker/node_modules/urllib/lib/urllib.js:733:14) at handleResponseCloseAndEnd (/opt/iobroker/node_modules/urllib/lib/urllib.js:913:7) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/urllib/lib/urllib.js:957:7) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12)
apple-find-me.0 | 2022-02-02 07:29:16.884 | error | unhandled promise rejection: The id "iPad." is invalid. Ids are not allowed to end in "."
apple-find-me.0 | 2022-02-02 07:29:16.883 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by PfisterDaniel** [comment]
Schau ich mir am, im nächsten Release sollte der Fehler dann behoben sein.

Danke fürs melden 👍

**Comment by fighterzg6** [comment]
super, danke für den adapter!

**Comment by AFPass** [comment]
Hallo,

Danke für den Adapter. Auf so einen warte ich schon ewig.
Leider ist der Fehler mit dem iPad noch aktuell.

**Comment by AFPass** [comment]
Scheinbar ist nur der Adapter mit der Instanz .0 betroffen.
Weitere Instanzen laufen ohne Probleme.

**Comment by AFPass** [comment]
Ich habe in meinem Fork den Fehler raus genommen.
Wenn keine DiscoveryID ermittelt werden kann, wird das Gerät nicht angelegt.
Zusätzlich merge ich Lat. und Long. in den neuen DP Position. Dann braucht man das später in Scripten nicht machen.

Kannst Du das übernehmen und ein neues Release erstellen?

**Comment by Apollon77** [comment]
Mach doch einen PR

**Comment by PfisterDaniel** [comment]
@AFPass
Danke für deine Unterstützung, ich wollte gerade schreiben, mach nen PR und ich schaus mir an. Alternativ kann ich aber auch deine Änderung direkt mit übernehmen.

Gruß Daniel

**Comment by AFPass** [comment]
> Mach doch einen PR

Was ist ein PR.
Bin froh das ich einen Fork hinbekommen habe und den Code lesen und anpassen konnte. 😂

**Comment by PfisterDaniel** [comment]
Is mein Source so schlecht? :-D

**Comment by AFPass** [comment]
> Is mein Source so schlecht? :-D

Nee. Sehr schön. Aber ich hab noch nie was mit JS gemacht.

**Comment by PfisterDaniel** [comment]
Release erstellt.

Danke nochmal für deine Unterstützung

Gruß Daniel

**Comment by Apollon77** [comment]
@AFPass Zur Benatwortung der Frage: Wenn DU schon einen Fork hast und was geändert und committet hast ... geht einfach auf die github seite. Dann zeigt er dir an das du x Commints vor dem original repo bist und hast nen "Contribute" button ... da kannst Du dann sagen "Pull Request anlegen" ... Aber Ihr habts ja schon gelöst :-)

**Comment by AFPass** [comment]
@PfisterDaniel Gerne. Brauch Ihn ja auch.
@Apollon77 Jep. Aber Danke für den Hinweis.

:-)

**Comment by AFPass** [comment]
@Apollon77 Der "alte" Adapter "Find my iPhone" (https://github.com/soef/ioBroker.find-my-iphone) sollte aus dem Repo von ioBroker gelöscht werden. Der funktioniert schon lange nicht mehr.
Dafür sollte dieser Adapter rein.

**Comment by Apollon77** [comment]
@PfisterDaniel Meldest Du deinen bitte fürs Repo an? Ind em Zuge am besten den alten rauslöschen. Ich weiss dann bescheid

**Comment by PfisterDaniel** [comment]
@Apollon77  gerne, sorry für die dumme frage aber gibts hier irgendwo ne simple Anleitung? Hab noch keinen Adapter im Repo veröffentlicht.

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository ... inkl. requirements und so weiter
