### ISSUE TITLE
Fehler beim Abrufen der Adresse von Google-Maps

### ISSUE THREAD

**Issue by Knallochse** [PfisterDaniel/ioBroker.apple-find-me#21]
Hallo und vielen Dank für deinen Adapter.

Funktioniert super.

Ich habe bei jeder Aktualisierung (5min) folgende Fehlermeldung

`<html>
<body>

apple-find-me.0 | 2022-05-13 07:05:10.530 | fehler | Fehler beim Abrufen der Adresse von Google-Maps
-- | -- | -- | --

</body>
</html>`

Wäre es möglich das Loglevel für diese Meldung als Warn bzw. Info und nicht Error auszugeben?

Grüße

**Comment by PfisterDaniel** [comment]
Hallo, ja das ist möglich. Ich werde es beim nächsten Release mit aufnehmen.

**Comment by Knallochse** [comment]
Hast die eine Idee, warum der Abruf der Adresse von Google Maps nicht funktioniert?

**Comment by Knallochse** [comment]
`< Error: REQUEST_DENIED >`

**Comment by PfisterDaniel** [comment]
Dann hast du vermutlich keinen gültigen API Key von Google genutzt

**Comment by PfisterDaniel** [comment]
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by Knallochse** [comment]
Der Key war korrekt, aber mir haben wohl API´s gefehlt. Jetzt geht es. Vielen Dank

**Comment by PfisterDaniel** [comment]
Ok, sehr gut.
Empfehlen kann ich aber die Here-Map API, die funktioniert meiner Erfahrung nach am besten. Google-Maps liefert öfter mal nen Zero-Result <- Wo er einfach mal nix findet. Warum auch immer.
