### ISSUE TITLE
HTTP-Request Fehler

### ISSUE THREAD

**Issue by Stefan-CH-87** [PfisterDaniel/ioBroker.apple-find-me#23]
Seit einigen Tagen erhalte ich folgenden Fehler im Log:
error: apple-find-me.2 (4628) Error on HTTP-Request. Please check your credentials. StatusCode: 401 Retry in 5 minutes. (1/3)

**Comment by Karatekid2407** [comment]
same here

**Comment by HackMe4Ever** [comment]
same here

**Comment by PfisterDaniel** [comment]
Now it works again. It seems to have been a mistake from Apple Service
