### ISSUE TITLE
Support for Apple AirTag

### ISSUE THREAD

**Issue by pehon** [PfisterDaniel/ioBroker.apple-find-me#24]
Hallo!
iPhone und iPad sehe ich, jedoch keine Apple AirTags.
Wäre es möglich, AirTags auch zu unterstützen?

Gruss,
Peter

**Comment by PfisterDaniel** [comment]
Hallo Peter,

Leider bietet Apple Find Me dies nicht an da ein AirTag immer an ein Gerät gebunden ist. AirTags lassen sich auch über die iCloud im Web nicht Orten. 

Gruß Daniel

**Comment by pehon** [comment]
schade, aber Danke für deine Antwort!
