### ISSUE TITLE
GPS Koordinaten werden nicht aktualisiert

### ISSUE THREAD

**Issue by AFPass** [PfisterDaniel/ioBroker.apple-find-me#25]
Ich habe mehrere Adapter von Apple-find-me eingebunden.
Bei den Adaptern .1 und .2 werden die GPS Koordinaten nicht mehr aktualisiert.

Der Zeitstempel ist akutell.

**Comment by AFPass** [comment]
Komisch. Seit Tagen kein Update. Jetzt geht es plötzlich wieder. 😮

**Comment by AFPass** [comment]
Komisch. Seit Tagen kein Update. Jetzt geht es plötzlich wieder. 😮

**Comment by AFPass** [comment]
Komisch. Seit Tagen kein Update. Jetzt geht es plötzlich wieder. 😮

**Comment by PfisterDaniel** [comment]
Es gab Probleme mit dem Apple Service. Ich hoffe das dass nur temporär war.
