### ISSUE TITLE
Air Tags

### ISSUE THREAD

**Issue by sredlin** [PfisterDaniel/ioBroker.apple-find-me#26]
Leider sehe ich nur iPhone, iPad und Watch und unter Apple Accessory's nur die AirPods Pro.
Bitte füge die AirTags mit hinzu.

**Comment by sredlin** [comment]
Feature Request bereits bekannt

**Comment by PfisterDaniel** [comment]
Leider ist das hinzufügen der AirTags aktuell nicht möglich. Da ein AirTag nicht an die iCloud sondern direkt an ein Gerät gekoppelt ist. Ich denke nicht das es in naher Zukunft hier eine Lösung geben wird. 

Gruß Daniel
