### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [PfisterDaniel/ioBroker.apple-find-me#3]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/PfisterDaniel/iobroker.apple-find-me

- [x] [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] [E004] No adapter name found in URL: https://raw.githubusercontent.com/PfisterDaniel/iobroker.apple-find-me/master
- [x] [E020] Name of adapter in package.json must be lowercase and be equal to "iobroker.". Now is "undefined"
- [x] [E019] Invalid repository URL: https://github.com/PfisterDaniel/ioBroker.apple-find-me. Expected: git+https://github.com/PfisterDaniel/iobroker.apple-find-me.git
- [x] [E103] common.name in io-package.json must be equal to "". Now is apple-find-me
- [x] [E145] No news found for actual version 0.0.5
- [x] [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [x] [E200] Not found on npm. Please publish
- [x] [E300] Not found on travis. Please setup travis
- [x] [E802] No topics found in the repository. Please go to "https://github.com/PfisterDaniel/iobroker.apple-find-me", press the settings button beside the about title and add some topics.
- [x] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 MasterDan <kontakt@daniel-pfister.de>" at the end of README.md
- [x] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 MasterDan <kontakt@daniel-pfister.de>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by PfisterDaniel** [comment]
All fixed

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
