### ISSUE TITLE
Removed devices from apple oud stay present in object tree

### ISSUE THREAD

**Issue by DutchmanNL** [PfisterDaniel/ioBroker.apple-find-me#9]
Behaviour:
I have my Apple ID already for couple of years and switched from phones.
The previous ones (unconnected from iCloud) are still shown in object tree.

Expeccted behavior:
Inactive/removed devices should not be shown

Acceptable workaround:
Make it possible in Adapter configuration to select for which devices states should be created, and by that ignore/delete the unselected ones

Cheers,

Dutch

**Comment by PfisterDaniel** [comment]
Hello Dutch,

You can delete the devices you no longer need in your icloud account:

![image](https://user-images.githubusercontent.com/9358627/159647438-bf776e73-66b9-4578-9c38-900665367653.png)
